### ISSUE TITLE
Crash when placing Better Builder's wand on hotbar

### ISSUE THREAD

**Issue by BrickVoid** [portablejim/BetterBuildersWands#24]
[crash-2017-01-05_12.51.02-client.txt](https://github.com/portablejim/BetterBuildersWands/files/686365/crash-2017-01-05_12.51.02-client.txt)
[crash-2017-01-05_13.16.31-client.txt](https://github.com/portablejim/BetterBuildersWands/files/686366/crash-2017-01-05_13.16.31-client.txt)

One of the above two crash reports shows the crash itself, when I experienced this crash, the last thing I was doing was placing the Better Builer's Wand (Iron) on the hotbar, where there was a stack of two Acacia Wood Planks from Biomes'o'Plenty.

People in a chat room who analyzed the crash log have written that there is a null pointer exception when it was expecting a true or false condition.  I have no idea if this is actually related to the crash report or not.

http://paste.feed-the-beast.com/view/c753973b

Above is the link to the log file containing the crash report which was generated in FTBPresentsDirewolf20110 modpack on their launcher, whilst I was playing it,  On line 4579 of that log is a java null pointer exception, and the crash report itself on line 4674.  As I wrote above, though, I've no idea if the two are related.

Apologies if this is confusing, hopefully you can sort out what is actually going on here.

Edit, it turns out there is an updated version of the modpack which fixes this crash.  Apologies, again, for any mixups or confusion.

**Comment by portablejim** [comment]
Already fixed. Update to a newer version.
