### ISSUE TITLE
Wand does not place blocks in 1.9

### ISSUE THREAD

**Issue by ProsperCraft** [portablejim/BetterBuildersWands#5]
Using BetterBuildersWands-0.6.0-1.9r124+c748dee

The wand finds its area, shows where it is going to place blocks, then doesn't place on click.

**Comment by tyler489** [comment]
works in SP not on servers using 0.6.1
Using knoxz test pack on the curse launcher

**Comment by portablejim** [comment]
Didn't realise it was 1.9 Servers.

**Comment by tyler489** [comment]
If i had to make a guess i would guess that this is depreciated in forge 1,9
  public Point3d move(ForgeDirection direction) {
        int newX = x, newY = y, newZ = z;
        switch(direction) {
