### ISSUE TITLE
[1.12-0.11.1.241+d18105e] Crash on launch

### ISSUE THREAD

**Issue by Kris1432** [portablejim/BetterBuildersWands#51]
Using forge 2331 for 1.12

Crashes when launching minecraft: https://pastebin.com/T7N0TdU1

**Comment by hextrace** [comment]
I'm having the same crash on load issue (https://paste.ee/p/XEOiU).

Forge 2334 for 1.12

Apparently `betterbuilderswands:wandiron` is being registered twice (evidenced in both crashlogs).

**Comment by nmkrupp** [comment]
still crashes after update on curse/twitch launcher
