### ISSUE TITLE
Add Botania IBlockProvider compatability

### ISSUE THREAD

**Issue by Dilnu** [portablejim/BetterBuildersWands#9]
Botania has an API to allow a single item to provide items to things like builder's wands. This would allow users to store blocks in a Black Hole Talisman (basically a portable deep storage unit) and thus build with a cleaner inventory among other options.

If that seems like a reasonable API to incorporate I'd be willing to write a pull request.

**Comment by portablejim** [comment]
Yes, it is a resonable API to incorporate. Having a pull request for the feature would be nice.

**Comment by Dilnu** [comment]
Created https://github.com/portablejim/BetterBuildersWands/pull/11

I hope I didn't do things wrong, this is the first time I've written a PR for a mod after a bunch of time spent browsing through various code bases.
